# Generated by Django 3.2.6 on 2022-01-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_alter_answer_text'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unit_items', to='study.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='items',
            field=models.ManyToManyField(through='study.Item', to='domain.Task'),
        ),
    ]
