# Generated by Django 3.2.6 on 2022-01-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20220104_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='topic',
        ),
        migrations.AddField(
            model_name='unit',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='study.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('n', 'Создан'), ('o', 'Открыт'), ('s', 'Начат'), ('f', 'Выполнен'), ('c', 'Истек')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='units',
            field=models.ManyToManyField(through='study.Unit', to='study.Module'),
        ),
    ]
