# Generated by Django 3.2.6 on 2022-01-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20220104_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='min_item',
            field=models.IntegerField(default=3),
        ),
    ]
