# Generated by Django 3.2.6 on 2022-01-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20220107_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['IID']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['TID']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['test__TID', 'order']},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='complete',
        ),
        migrations.AddField(
            model_name='item',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='complete_status',
            field=models.CharField(choices=[('n', 'Не начат'), ('a', 'В процессе'), ('f', 'Завершен')], default='n', max_length=1),
        ),
    ]
