# Generated by Django 3.2.6 on 2022-01-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20220107_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valid',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
