# Generated by Django 3.2.6 on 2022-01-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_item_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='analysis',
            field=models.CharField(choices=[('n', 'Не требуется'), ('t', 'В ожидании'), ('d', 'Сделано')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('n', 'Ответ отсутствует'), ('r', 'Правильно'), ('c', 'Неправильно, понятно'), ('u', 'Неправильно, не понятно'), ('d', 'Затруднение с ответом'), ('i', 'Некорректный ответ')], default='n', max_length=1),
        ),
    ]
