# Generated by Django 3.2.6 on 2022-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20220118_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='dev',
            field=models.BooleanField(default=False, verbose_name='Для тестирования'),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Продолжительность темы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='min_item',
            field=models.IntegerField(default=3, verbose_name='Минимальное количество заданий'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_close',
            field=models.DateTimeField(null=True, verbose_name='Срок выполнения'),
        ),
    ]
