# Generated by Django 3.2.6 on 2022-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_auto_20220120_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='response',
            field=models.CharField(max_length=256, null=True, verbose_name='Введите ответ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('n', 'Ответ отсутствует'), ('r', 'Правильно'), ('c', 'Неправильно, понятно'), ('u', 'Неправильно, не понятно'), ('d', 'Затруднение с ответом'), ('i', 'Отправлен на модерацию')], default='n', max_length=1),
        ),
    ]
