# Generated by Django 3.2.6 on 2022-01-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20220121_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_units', to='study.test'),
        ),
    ]
