# Generated by Django 3.2.6 on 2022-01-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0006_auto_20220117_1411'),
        ('study', '0006_alter_item_valid'),
        ('als', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemfeature',
            options={'ordering': ['item__IID']},
        ),
        migrations.AlterModelOptions(
            name='modulefeature',
            options={'ordering': ['module__MID']},
        ),
        migrations.AlterModelOptions(
            name='studentfeature',
            options={'ordering': ['student__SID']},
        ),
        migrations.AlterModelOptions(
            name='taskfeature',
            options={'ordering': ['task__code']},
        ),
        migrations.AlterModelOptions(
            name='testfeature',
            options={'ordering': ['test__TID']},
        ),
        migrations.AlterModelOptions(
            name='topicfeature',
            options={'ordering': ['topic__code']},
        ),
        migrations.AlterModelOptions(
            name='unitfeature',
            options={'ordering': ['unit__UID']},
        ),
        migrations.CreateModel(
            name='UnitParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_RPRT', models.FloatField(default=0)),
                ('unit_RMCAT', models.FloatField(default=0)),
                ('unit_RMCRT', models.FloatField(default=0)),
                ('unit_RRCRtoCA', models.FloatField(default=0)),
                ('unit_RMCAtoPR', models.FloatField(default=0)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.unit')),
            ],
            options={
                'ordering': ['unit__test__TID', 'unit__order'],
            },
        ),
        migrations.CreateModel(
            name='StudentParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_PRT', models.FloatField(default=0)),
                ('student_MCET', models.FloatField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lk.student')),
            ],
            options={
                'ordering': ['student__SID'],
            },
        ),
        migrations.CreateModel(
            name='ModuleParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_LPEG', models.FloatField(default=0)),
                ('module_LPET', models.FloatField(default=0)),
                ('module_LPRT', models.FloatField(default=0)),
                ('module_LGPET', models.JSONField()),
                ('module_LGPRT', models.JSONField()),
                ('module_RPRT', models.FloatField(default=0)),
                ('module_RMCAT', models.FloatField(default=0)),
                ('module_RMCRT', models.FloatField(default=0)),
                ('module_RMCR5T', models.FloatField(default=0)),
                ('module_RRCRtoCA', models.FloatField(default=0)),
                ('module_RMCAtoPR', models.FloatField(default=0)),
                ('module_color', models.CharField(choices=[('g', 'Успешность последнего теста выше предпоследнего и за всю историю'), ('r', 'Успешность последнего теста ниже предпоследнего и за всю историю'), ('p', 'Успешность последнего теста ниже предпоследнего'), ('e', '-')], default='e', max_length=1)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.module')),
            ],
            options={
                'ordering': ['module__student__SID', 'module__order'],
            },
        ),
    ]
