# Generated by Django 3.2.6 on 2022-01-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0002_auto_20220117_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_LGPET',
            new_name='LGPET',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_LGPRT',
            new_name='LGPRT',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_LPEG',
            new_name='LPEG',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_LPET',
            new_name='LPET',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_LPRT',
            new_name='LPRT',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_RMCAT',
            new_name='RMCAT',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_RMCAtoPR',
            new_name='RMCAtoPR',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_RMCR5T',
            new_name='RMCR5T',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_RMCRT',
            new_name='RMCRT',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_RPRT',
            new_name='RPRT',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_RRCRtoCA',
            new_name='RRCRtoCA',
        ),
        migrations.RenameField(
            model_name='moduleparam',
            old_name='module_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='studentparam',
            old_name='student_MCET',
            new_name='MCET',
        ),
        migrations.RenameField(
            model_name='studentparam',
            old_name='student_PRT',
            new_name='PRT',
        ),
        migrations.RenameField(
            model_name='unitparam',
            old_name='unit_RMCAT',
            new_name='RMCAT',
        ),
        migrations.RenameField(
            model_name='unitparam',
            old_name='unit_RMCAtoPR',
            new_name='RMCAtoPR',
        ),
        migrations.RenameField(
            model_name='unitparam',
            old_name='unit_RMCRT',
            new_name='RMCRT',
        ),
        migrations.RenameField(
            model_name='unitparam',
            old_name='unit_RPRT',
            new_name='RPRT',
        ),
        migrations.RenameField(
            model_name='unitparam',
            old_name='unit_RRCRtoCA',
            new_name='RRCRtoCA',
        ),
    ]
