# Generated by Django 3.2.6 on 2022-01-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0004_auto_20220117_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleparam',
            old_name='LGPET',
            new_name='LGPT',
        ),
        migrations.RemoveField(
            model_name='moduleparam',
            name='LGPRT',
        ),
    ]
