# Generated by Django 3.2.6 on 2022-01-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0005_auto_20220117_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleparam',
            name='LGPT',
            field=models.JSONField(null=True),
        ),
    ]
