# Generated by Django 3.2.6 on 2022-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0006_alter_moduleparam_lgpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleparam',
            name='LPEG',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleparam',
            name='LPET',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleparam',
            name='LPRT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleparam',
            name='RMCAT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleparam',
            name='RMCAtoPR',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleparam',
            name='RMCR5T',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleparam',
            name='RMCRT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleparam',
            name='RPRT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleparam',
            name='RRCRtoCA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentparam',
            name='MCET',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentparam',
            name='PRT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unitparam',
            name='RMCAT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unitparam',
            name='RMCAtoPR',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unitparam',
            name='RMCRT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unitparam',
            name='RPRT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unitparam',
            name='RRCRtoCA',
            field=models.FloatField(null=True),
        ),
    ]
