# Generated by Django 3.2.6 on 2022-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0007_auto_20220120_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleparam',
            name='PRT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unitparam',
            name='PRT',
            field=models.FloatField(null=True),
        ),
    ]
