# Generated by Django 3.2.6 on 2022-01-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0008_auto_20220121_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleparam',
            name='PRT',
        ),
    ]
