# Generated by Django 3.2.6 on 2022-01-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0010_remove_unitparam_prt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentparam',
            name='MRPRT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moduleparam',
            name='color',
            field=models.CharField(choices=[('g', '#98FB98'), ('r', '#FFB6C1'), ('p', '#fcebec'), ('e', '#FFFFFF')], default='e', max_length=1),
        ),
    ]
