# Generated by Django 3.2.6 on 2021-09-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(
                    choices=[('f', 'Произвольный ответ'), ('c', 'Выбор'), ('x', 'Математическое выражение'),
                             ('w', 'Математическое выражение с ошибками'), ('p', 'Точка'), ('y', 'Да/нет'),
                             ('i', 'Интервал'), ('n', 'Неравенство'), ('e', 'Равенство'), ('r', 'Текст (кириллица)'),
                             ('m', 'Соответствие')], default='f', max_length=1)),
                ('text', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AnswerChoice',
        ),
        migrations.DeleteModel(
            name='AnswerCyrillic',
        ),
        migrations.DeleteModel(
            name='AnswerEquality',
        ),
        migrations.DeleteModel(
            name='AnswerFree',
        ),
        migrations.DeleteModel(
            name='AnswerInequality',
        ),
        migrations.DeleteModel(
            name='AnswerInterval',
        ),
        migrations.DeleteModel(
            name='AnswerMatch',
        ),
        migrations.DeleteModel(
            name='AnswerMathExp',
        ),
        migrations.DeleteModel(
            name='AnswerMathWrong',
        ),
        migrations.DeleteModel(
            name='AnswerPoint',
        ),
        migrations.DeleteModel(
            name='AnswerYesno',
        ),
        migrations.RemoveField(
            model_name='task',
            name='checked',
        ),
        migrations.AddField(
            model_name='task',
            name='moderation_status',
            field=models.CharField(choices=[('u', 'Не проверено'), ('p', 'В процессе'), ('c', 'Проверено')],
                                   default='u', max_length=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.task'),
        ),
    ]
