# Generated by Django 3.2.6 on 2021-09-15 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('domain', '0002_auto_20210914_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='for_current',
            new_name='learning',
        ),
    ]
