# Generated by Django 3.2.6 on 2021-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_rename_for_current_task_learning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
