# Generated by Django 3.2.6 on 2022-01-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_alter_answer_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['code']},
        ),
    ]
