# Generated by Django 3.2.6 on 2022-01-24 15:39

from django.db import migrations, models
import django.db.models.deletion
import domain.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_alter_answer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expert_level',
            field=models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=0, verbose_name='Экспертная оценка сложности'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.IntegerField(default=-1, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, upload_to=domain.models.taskimgpath, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='learning',
            field=models.BooleanField(default=False, verbose_name='Для изучения?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код темы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='grade',
            field=models.IntegerField(choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], default=5, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название темы'),
        ),
    ]
