# Generated by Django 3.2.6 on 2021-08-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0002_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='PID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
