# Generated by Django 3.2.6 on 2022-01-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['SID']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['PID']},
        ),
    ]
